### ISSUE TITLE
[SOLVED] UPnP: Automatic generation of .h files from XML

### ISSUE THREAD

**Issue by slaff** [slaff/SmingSwitch#1]
@mikee47 For a Sming sample project I have created a XML device and service files (https://github.com/slaff/SmingSwitch/tree/master/schema/schemas-sming-org). Now I would like to generate automatically .h files. How can I do this?

See the comments for the solution.
Some notes:
- Location of the .h and .cpp files:
The .h and .cpp files will be generated in the global build directory. The directory location can be found by typing `make list-config` and looking at the prerequisites to find the desired directory. Example
```
PREREQUISITES
- /opt/Sming/Sming/out/Host/debug/build/UPnP-Schema/.gen
CUSTOM_TARGETS
...
```
   From the excerpt above the build directory for the schema is `/opt/Sming/Sming/out/Host/debug/build/UPnP-Schema/`. 

- .h and .cpp regeneration:
If the original device or service(s) XML files are updated then no .h and .cpp files will be re-generated. One way to regenerate, unfortunately all, .h and .cpp files for the schemas is to run: `make UPnP-Schema-clean` and the run again `make`.

**Comment by mikee47** [comment]
@slaff Just run a regular `make`, these will get generated as part of the `UPnP-Schema` Component, `$SMING_HOME/out/Esp8266/debug/build/UPnP-Schema/src/Network/UPnP/schemas-sming-org/...`.

In your `SmingSwitch1.xml` file, `deviceType` should be `urn:schemas-sming-org:device:SmingSwitch:1`. (i.e. `SmingSwitch`, not `Switch`). This is used for filenames so probably need a make `UPnP-Schema-clean` to clear out the old one.

Also, delete `SwitchPower1.xml`. This is a standard service already defined in the library.

**Comment by slaff** [comment]
@mikee47 Is it possible to regenerate .h and .cpp files only for the SmingSwitch and co XML files?

**Comment by mikee47** [comment]
@slaff Not at present. However, if you edit `$SMING_HOME/Libraries/UPnP-Schema/component.mk` and remove line #30 (touch S@) it'll pick up any changes in the source XML and rebuilt automatically. That line is there to try not to bog the build down too much (mainly in Windows). In Linux it's not an issue so perhaps things like that could be made conditional. Not sure about MacOS since I've so far failed to get build tools installed on my sierra VM.

**Comment by slaff** [comment]
> it'll pick up any changes in the source XML and rebuilt automatically.

Wow! It would be great to have a flag controlling this behaviour. For example UPNP_SCHEMA_AUTOREBUILD which is by default 0 (as is currently the case but can be changed from the user to 1 )

**Comment by mikee47** [comment]
It's a similar situation for which `FULL_COMPONENT_BUILD` was added, avoiding running all sub-makes on every build...

**Comment by mikee47** [comment]
... so `$(findstring UPNP_SCHEMA,$(FULL_COMPONENT_BUILD))` could be used to trigger this behaviour for consistency.

**Comment by mikee47** [comment]
I'll start some updates for UPnP-Schema.

There are a lot of other standard schemas which aren't in the library - see https://openconnectivity.org/developer/specifications/upnp-resources/upnp/. In particular, the `HVAC:1` may define services which are more appropriate to your use?

An issue with the current structure is that a group contains everything for a single domain, and for `schemas-upnp-org` that's a lot! What I'm thinking of doing is breaking that up further so within each domain we have separate groups defined for `Cloud`, `Device Management`, `Home Automation` and so on.

**Comment by mikee47** [comment]
Regarding your SmingSwitch project, I note you've mixed lighting, temperature and humidity within a single interface. Would it be better to use group related functions into separate services? Also, there's stuff in [HVAC](https://openconnectivity.org/developer/specifications/upnp-resources/upnp/hvac-v-1-0/) to handle temperature monitoring but maybe it's a bit complex...

**Comment by mikee47** [comment]
I've pushed commits to the develop branch of UPnP and UPnP-Schema, so if you'd like to work with those we can update Sming at a suitable point.

**Comment by slaff** [comment]
> Also, there's stuff in HVAC to handle temperature monitoring but maybe it's a bit complex...

Yeah, the services may not be well organized but I wanted something simple to start with. Also the TH16 from Sonoff has a temperature and humidity sensor but does not allow  you to set the temperature, as a Honeywell air conditioner. 

> I've pushed commits to the develop branch of UPnP and UPnP-Schema, so if you'd like to work with those we can update Sming at a suitable point.

Let's add them to Sming. Ping me when ready for merging.
